ALTER TABLE [dbo].[EmployeesData]
    ADD CONSTRAINT [PK_EmployeesData] PRIMARY KEY CLUSTERED ([EmployeeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

